spring:
  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/pennypulse}
    username: ${DB_USER:pennypulse}
    password: ${DB_PASSWORD:pennypulse}
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
  flyway:
    enabled: true

server:
  port: ${PORT:8080}

management:
  endpoints:
    web:
      exposure:
        include: health,info
